module.exports = {
  apps: [
    {
      name: "rw-translate-api",
      script: "/data/workspace/Rusted-Workshop-Translation-API/.venv/bin/python",
      args: "-m uvicorn api.main:app --host 0.0.0.0 --port 8001 --log-level info",
      cwd: "/data/workspace/Rusted-Workshop-Translation-API",
      env: {
        DOTENV_CONFIG_PATH: "/data/workspace/Rusted-Workshop-Translation-API/.env",
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      watch: false,
      max_memory_restart: "512M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/data/workspace/Rusted-Workshop-Translation-API/logs/pm2-api-error.log",
      out_file: "/data/workspace/Rusted-Workshop-Translation-API/logs/pm2-api-out.log",
    },
    {
      name: "rw-translate-coordinator",
      script: "/data/workspace/Rusted-Workshop-Translation-API/.venv/bin/python",
      args: "-m workers.coordinator_worker",
      cwd: "/data/workspace/Rusted-Workshop-Translation-API",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      watch: false,
      max_memory_restart: "512M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/data/workspace/Rusted-Workshop-Translation-API/logs/pm2-coordinator-error.log",
      out_file: "/data/workspace/Rusted-Workshop-Translation-API/logs/pm2-coordinator-out.log",
    },
    {
      name: "rw-translate-file-worker",
      script: "/data/workspace/Rusted-Workshop-Translation-API/.venv/bin/python",
      args: "-m workers.file_translation_worker",
      cwd: "/data/workspace/Rusted-Workshop-Translation-API",
      instances: 5,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      watch: false,
      max_memory_restart: "512M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/data/workspace/Rusted-Workshop-Translation-API/logs/pm2-file-worker-error.log",
      out_file: "/data/workspace/Rusted-Workshop-Translation-API/logs/pm2-file-worker-out.log",
    },
    {
      name: "rw-translate-cleanup",
      script: "/data/workspace/Rusted-Workshop-Translation-API/.venv/bin/python",
      args: "start_cleanup.py",
      cwd: "/data/workspace/Rusted-Workshop-Translation-API",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      watch: false,
      max_memory_restart: "256M",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/data/workspace/Rusted-Workshop-Translation-API/logs/pm2-cleanup-error.log",
      out_file: "/data/workspace/Rusted-Workshop-Translation-API/logs/pm2-cleanup-out.log",
    },
  ],
};
